src/PagingDemo.Web/ViewModels/ProductListViewModel.cs
using cloudscribe.Pagination.Models;
using PagingDemo.Web.Models;

namespace PagingDemo.Web.ViewModels
{
    public class ProductListViewModel
    {
        public ProductListViewModel()
        {
            Products = new PagedResult<Product>();
        }

        public string Query { get; set; } = string.Empty;

        public PagedResult<Product> Products { get; set; } = null;

        
    }
}

src/PagingDemo.Web/Controllers/PagingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PagingDemo.Web.Models;
using PagingDemo.Web.ViewModels;



namespace PagingDemo.Web.Controllers
{
    public class PagingController : Controller
    {
        private const int DefaultPageSize = 10;
        private List<Product> allProducts = new List<Product>();
        private readonly string[] allCategories = new string[3] { "Shoes", "Electronics", "Food" };

        public PagingController()
        {
            InitializeProducts();
        }

        private void InitializeProducts()
        {
            // Create a list of products. 50% of them are in the Shoes category, 25% in the Electronics 
            // category and 25% in the Food category.
            for (var i = 0; i < 527; i++)
            {
                var product = new Product();
                product.Name = "Product " + (i + 1);
                var categoryIndex = i % 4;
                if (categoryIndex > 2)
                {
                    categoryIndex = categoryIndex - 3;
                }
                product.Category = allCategories[categoryIndex];
                allProducts.Add(product);
            }
        }

       // [Route("paging/{page?}")]
        public IActionResult Index(int p = 1)
        {
            
            var currentPageNum = p;
            var offset = (DefaultPageSize * currentPageNum) - DefaultPageSize;
            var model = new ProductListViewModel();
            model.Products.Data = this.allProducts
                .Skip(offset)
                .Take(DefaultPageSize)
                .ToList();

            model.Products.PageNumber = currentPageNum;
            model.Products.PageSize = DefaultPageSize;
            model.Products.TotalItems = allProducts.Count;

            
            return View(model);

            
        }

        public IActionResult ProductList(
            int? pageNumber, 
            int? pageSize,
            string query = "")
        {
            var itemsPerPage = pageSize.HasValue ? pageSize.Value : DefaultPageSize;
            var currentPageNum = pageNumber.HasValue ? pageNumber.Value  : 1;
            var offset = (itemsPerPage * currentPageNum) - itemsPerPage;
            var model = new ProductListViewModel();

            var filtered = this.allProducts.Where(p =>
                p.Category.StartsWith(query)
                );

            model.Products.Data = filtered
                .Skip(offset)
                .Take(itemsPerPage)
                .ToList();

            model.Products.PageNumber = currentPageNum;
            model.Products.PageSize = itemsPerPage;
            model.Products.TotalItems = filtered.ToList().Count;
            model.Query = query; //TODO: sanitize

            return View(model);


        }

        public IActionResult BlogPagingDemo(
            int? pageNumber,
            string query = "")
        { 
            int itemsPerPage = 1;

            var currentPageNum = pageNumber.HasValue ? pageNumber.Value : 1;
            var offset = (itemsPerPage * currentPageNum) - itemsPerPage;

            var filtered = allProducts.Where(p =>
                p.Category.StartsWith(query)
            )
            .OrderByDescending(p => p.CreatedUtc)
            .ToList();
            
            var model = new ProductListViewModel();

            model.Products.Data = filtered
            .Skip(offset)
            .Take(itemsPerPage)
            .ToList();

            model.Products.PageNumber = currentPageNum;
            model.Products.PageSize = itemsPerPage;
            model.Products.TotalItems = filtered.Count;
            //model.Paging.UseReverseIncrement = true;
            model.Query = query; //TODO: sanitize

            return View(model);


        }

        public IActionResult ViewByCategory(string categoryName, int? page)
        {
            categoryName = categoryName ?? this.allCategories[0]; 
            var currentPageNum = page.HasValue ? page.Value : 1;
            var offset = (DefaultPageSize * currentPageNum) - DefaultPageSize;

            var filtered = this.allProducts.Where(p =>
                p.Category.Equals(categoryName)
                ).ToList();

            var model = new ProductListViewModel();

            model.Products.Data = filtered
                .Skip(offset)
                .Take(DefaultPageSize)
                .ToList();

            model.Products.PageNumber = currentPageNum;
            model.Products.PageSize = DefaultPageSize;
            model.Products.TotalItems = filtered.Count;

            ViewBag.CategoryName = new SelectList(this.allCategories, categoryName);
            ViewBag.CategoryDisplayName = categoryName;

            return View("ProductsByCategory", model);
        }

        

        public IActionResult ViewByCategories(string[] categories, int? page)
        {
            // I have not figured out how to convert a string array to routeparam
            // in mvc6 yet so the categories may be passed as a single csv string

            if(categories != null)
            {
                if((categories.Length == 1) &&(categories[0].Contains(",")))
                {
                    categories = categories[0].Split(',');
                }
            }

            var currentPageNum = page.HasValue ? page.Value : 1;
            var offset = (DefaultPageSize * currentPageNum) - DefaultPageSize;

            var model = new ViewByCategoriesViewModel();
            model.Categories = categories ?? new string[0];
            int currentPageIndex = page.HasValue ? page.Value - 1 : 0;

            var filtered = this.allProducts.Where(p =>
                model.Categories.Contains(p.Category)
                ).ToList();

            model.Products.Data = filtered
                .Skip(offset)
                .Take(DefaultPageSize)
                .ToList();
                
            model.AvailableCategories = this.allCategories;

            model.Products.PageNumber = currentPageNum;
            model.Products.PageSize = DefaultPageSize;
            model.Products.TotalItems = filtered.Count;
           
            return View("ProductsByCategories", model);
        }

        
        public IActionResult IndexAjax()
        {
            
            var model = new ProductListViewModel();

            model.Products.Data = this.allProducts
                .Take(DefaultPageSize)
                .ToList();
            

            model.Products.PageNumber = 1;
            model.Products.PageSize = DefaultPageSize;
            model.Products.TotalItems = allProducts.Count;

            if (HttpContext.Request.IsAjaxRequest())
            {
               
                return PartialView("_PagingModal", model);
            }
            return View(model);
        }

        //[Route("paging/ajaxpage/{page?}")]
        public async Task<IActionResult> AjaxPage(int? page)
        {
            ViewBag.Title = "Browse all products";
            
            var currentPageNum = page.HasValue ? page.Value : 1;
            var offset = (DefaultPageSize * currentPageNum) - DefaultPageSize;

            var model = new ProductListViewModel();

            model.Products.Data = this.allProducts
                .Skip(offset)
                .Take(DefaultPageSize)
                .ToList();

            model.Products.PageNumber = currentPageNum;
            model.Products.PageSize = DefaultPageSize;
            model.Products.TotalItems = allProducts.Count;

            // simulate delay to show the loadinng indicator
            await Task.Delay(2000);//milliseconds

            return PartialView("_ProductGrid", model);
        }


    }
}

src/PagingDemo.Web/Views/Paging/BlogPagingDemo.cshtml
@using cloudscribe.Web.Pagination
@using PagingDemo.Web.ViewModels
@using PagingDemo.Web.Models

@model ProductListViewModel
@{
    ViewBag.Title = "Browse all products with ViewModel";
}
<h2>@ViewBag.Title</h2>
<p>
    This demo uses alphabetic pager/filter in conjunction with a pager.
    If you click a letter that matches the start of a product category it
    will filter to matching items and the pager will preserve that filter while paging.
    The only categories are Food, Electronics, and Shoes, so only F, E, or S will show any products.
    You can also manipulate the pageSize param in the url.
</p>

<div>
    <cs-alphapager cs-alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                   cs-selected-letter="@Model.Query"
                   cs-all-label="All"
                   asp-controller="Paging"
                   asp-action="BlogPagingDemo"
                   cs-selected-letter-param="query"></cs-alphapager>
</div>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Product name</th>
            <th>Category</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Products.Data)
        {
            <tr>
                <td>@product.Name</td>
                <td>@product.Category</td>
            </tr>}
    </tbody>
</table>
<div>
    <cs-pager cs-paging-pagesize="@Model.Products.PageSize"
              cs-paging-pagenumber="@Model.Products.PageNumber"
              cs-paging-totalitems="@Model.Products.TotalItems"
              cs-pagenumber-param="pageNumber"
              cs-paging-maxpageritems="0"
              cs-show-first-last="false"
              cs-show-numbered="false"
              cs-use-reverse-increment="true"
              cs-suppress-empty-nextprev="true"
              cs-previous-page-text="< Older"
              cs-next-page-text="Newer >"
              asp-controller="Paging"
              asp-action="BlogPagingDemo"
              asp-route-query="@Model.Query"></cs-pager>
</div>

src/PagingDemo.Web/Views/Paging/Index.cshtml
@using cloudscribe.Web.Pagination
@using PagingDemo.Web.ViewModels
@using PagingDemo.Web.Models

@model ProductListViewModel
@{
    ViewBag.Title = "Browse all products with Model";
}
<h2>@ViewBag.Title</h2>
<p>
    <a class="btn btn-xs btn-default" 
       asp-action="IndexAjax" asp-controller="Paging"
       bs-modal-link="true">Ajax Modal</a>
</p>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Product name</th>
            <th>Category</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Products.Data)
        {
            <tr>
                <td>@product.Name</td>
                <td>@product.Category</td>
            </tr>}
    </tbody>
</table>
<div>
    <cs-pager cs-paging-pagesize="@Model.Products.PageSize"
              cs-paging-pagenumber="@Model.Products.PageNumber"
              cs-paging-totalitems="@Model.Products.TotalItems"
              cs-pagenumber-param="p"
              cs-show-first-last="true"
              cs-suppress-empty-nextprev="true"
              cs-remove-nextprev-links="false"
              cs-suppress-inactive-firstlast="true"
              cs-first-page-text="First"
              cs-last-page-text="Last"
              cs-pager-li-current-class="active"
              cs-pager-li-non-active-class="disabled"
              asp-route="pagingdemo1"
              asp-controller="Paging"
              asp-action="Index" cs-preserve-ambient-querystring="false"></cs-pager>

    
</div>

<div>
    <p> this one automatic generate url from your current Action and Controller </p>
    <cs-pager cs-paging-pagesize="@Model.Products.PageSize"
              cs-paging-pagenumber="@Model.Products.PageNumber"
              cs-paging-totalitems="@Model.Products.TotalItems"
              cs-pagenumber-param="p"></cs-pager>
</div>

@section Scripts {

<script type="text/javascript">

        function PagerRequestSuccess(data) {
            //console.log("This is the OnSuccessCallback: " + data);
            console.log("This is the OnSuccessCallback");
        }
        function PagerRequestFailure(request, error) {
            console.log("This is the OnFailure Callback:" + error);
        }

</script>


    <environment names="Development">
        <script src="~/js/jquery.unobtrusive-ajax.js"></script>
        <script src="~/jsdev/cloudscribe-modaldialog-bootstrap.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/jquery.unobtrusive-ajax.min.js"></script>
        <script src="~/jsdev/cloudscribe-modaldialog-bootstrap.js"></script>
    </environment>


}

src/PagingDemo.Web/Views/Paging/IndexAjax.cshtml
@using cloudscribe.Web.Pagination
@using PagingDemo.Web.ViewModels
@using PagingDemo.Web.Models

@model ProductListViewModel
@{
    ViewBag.Title = "Browse all products (ajax)";
}
<h2>@ViewBag.Title</h2>
<div id="gridcontainer">
    <partial name="_ProductGrid" model="Model" />
</div>
<div id="loadingIndicator" style="background-color:cadetblue; display:none">
    <p>Loading...</p>
</div>

@section Scripts {

<script type="text/javascript">
        
        function PagerRequestSuccess(data) {
            //console.log("This is the OnSuccessCallback: " + data);
            console.log("This is the OnSuccessCallback");
        }
        function PagerRequestFailure(request, error) {
            console.log("This is the OnFailure Callback:" + error);
        }
        
</script>

    <environment names="Development">
        <script src="~/js/jquery.unobtrusive-ajax.js"></script>
        
        <script src="~/jsdev/cloudscribe-modaldialog-bootstrap.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/jquery.unobtrusive-ajax.min.js"></script>
        
        <script src="~/jsdev/cloudscribe-modaldialog-bootstrap.js"></script>
    </environment>


}

src/PagingDemo.Web/Views/Paging/ProductList.cshtml
@using cloudscribe.Web.Pagination
@using PagingDemo.Web.ViewModels
@using PagingDemo.Web.Models

@model ProductListViewModel
@{
    ViewBag.Title = "Browse all products with ViewModel";
}
<h2>@ViewBag.Title</h2>
<p>This demo uses alphabetic pager/filter in conjunction with a pager.
    If you click a letter that matches the start of a product category it 
    will filter to matching items and the pager will preserve that filter while paging.
    The only categories are Food, Electronics, and Shoes, so only F, E, or S will show any products.
    You can also manipulate the pageSize param in the url.</p>

<div>
    <cs-alphapager cs-alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                   cs-selected-letter="@Model.Query"
                   cs-all-label="All"
                   asp-controller="Paging"
                   asp-action="ProductList" 
                   cs-selected-letter-param="query"
                   ></cs-alphapager>
</div>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Product name</th>
            <th>Category</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Products.Data)
        {
            <tr>
                <td>@product.Name</td>
                <td>@product.Category</td>
            </tr>}
    </tbody>
</table>
<div>
    <cs-pager cs-paging-pagesize="@Model.Products.PageSize"
              cs-paging-pagenumber="@Model.Products.PageNumber"
              cs-paging-totalitems="@Model.Products.TotalItems"
              cs-pagenumber-param="pageNumber"
              asp-controller="Paging"
              cs-previous-page-html="<a href='#' title='Previous page'><i class='glyphicon glyphicon-backward'></i></a>"
              cs-next-page-html="<a href='#' title='Next page'><i class='glyphicon glyphicon-forward'></i></a>"
              asp-action="ProductList" 
              asp-route-query="@Model.Query"
              asp-route-pagesize="@Model.Products.PageSize"></cs-pager>
</div>

src/PagingDemo.Web/Views/Paging/ProductsByCategories.cshtml
@using System.Linq
@using PagingDemo.Web.Models
@using PagingDemo.Web.ViewModels

@model ViewByCategoriesViewModel
@{
    ViewBag.Title = "Browse products by categories";
}
<h2>@ViewBag.Title</h2>
<form class="form-inline" role="form" asp-controller="Paging" asp-action="ViewByCategories" method="get" asp-antiforgery="false">
    Select category or categories:
    <ul>
        @foreach (var category in Model.AvailableCategories)
        {
            <li>
                <label>
                    <input type="checkbox" name="categories" value="@category" @if (Model.Categories.Any(c => c == category)) { <text> checked="checked" </text>   } />
                    @category
                </label>
            </li>}
    </ul>
    <input type="submit" value="Browse" class="btn btn-default" />

</form>
   
    @if (Model.Products.Data.Any())
    {
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Product name</th>
                    <th>Category</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var product in Model.Products.Data)
                {
                    <tr>
                        <td>@product.Name</td>
                        <td>@product.Category</td>
                    </tr>}
            </tbody>
        </table>
        <cs-pager cs-paging-pagesize="@Model.Products.PageSize"
                  cs-paging-pagenumber="@Model.Products.PageNumber"
                  cs-paging-totalitems="@Model.Products.TotalItems"
                  cs-pagenumber-param="page"
                  asp-controller="Paging"
                  asp-action="ViewByCategories"
                  asp-route-categories="@Model.Categories.ToCsv()"
                  asp-route-pagesize="@Model.Products.PageSize"
                  cs-first-page-text="First"
                  cs-last-page-text="Last"
                  cs-previous-page-text="Prev"
                  cs-next-page-text="Next"></cs-pager>

            
    }

src/PagingDemo.Web/Views/Paging/ProductsByCategory.cshtml
@using cloudscribe.Web.Pagination
@using PagingDemo.Web.ViewModels
@using PagingDemo.Web.Models

@model ProductListViewModel
@{
    ViewBag.Title = "Browse products by category";
}
<h2>@ViewBag.Title</h2>

<form class="form-inline" role="form" asp-controller="Paging" asp-action="ViewByCategory" method="get" asp-antiforgery="false">
            
        Select a category:
        @Html.DropDownList("categoryName",null, new { @class = "form-control" } )
        <button type="submit" class="btn btn-default">Browse</button>   
</form>
       
 
    @if (Model.Products.Data.Count > 0)
    {
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Product name</th>
                    <th>Category</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var product in Model.Products.Data)
                {
                    <tr>
                        <td>@product.Name</td>
                        <td>@product.Category</td>
                    </tr>}
            </tbody>
        </table>
        <div>
            <cs-pager cs-paging-pagesize="@Model.Products.PageSize"
                      cs-paging-pagenumber="@Model.Products.PageNumber"
                      cs-paging-totalitems="@Model.Products.TotalItems"
                      cs-pagenumber-param="page"
                      asp-controller="Paging"
                      asp-action="ViewByCategory"
                      asp-route-categoryname="@ViewBag.CategoryDisplayName"
                      asp-route-pagesize="@Model.Products.PageSize"></cs-pager>

        </div>
        

    }

src/PagingDemo.Web/Views/Paging/_PagingModal.cshtml
@using cloudscribe.Web.Pagination
@using PagingDemo.Web.ViewModels
@using PagingDemo.Web.Models

@model ProductListViewModel
@{
    ViewBag.Title = "Browse all products (ajax)";
}

<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="CommonResources.Close"><span aria-hidden="true">&times;</span></button>
            <h2 class="modal-title" id="myModalLabel">My Modal</h2>
        </div>
        <div class="modal-body">
            <h3>@ViewBag.Title</h3>

            <div id="gridcontainer">
                <partial name="_ProductGrid" model="Model" />
            </div>
            <div id="loadingIndicator" style="background-color:cadetblue; display:none">
                <p>Loading...</p>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>

src/PagingDemo.Web/Views/Paging/_ProductGrid.cshtml
@using cloudscribe.Web.Pagination
@using PagingDemo.Web.ViewModels
@using PagingDemo.Web.Models

@model ProductListViewModel
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Product name</th>
            <th>Category</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model.Products.Data)
        {
            <tr>
                <td>@product.Name</td>
                <td>@product.Category</td>
            </tr>}
    </tbody>
</table>
<div>
    <cs-pager cs-paging-pagesize="@Model.Products.PageSize"
              cs-paging-pagenumber="@Model.Products.PageNumber"
              cs-paging-totalitems="@Model.Products.TotalItems"
              cs-pagenumber-param="page"
              cs-ajax-target="#gridcontainer"
              cs-ajax-loading="#loadingIndicator"
              cs-ajax-loading-duration="10"
              cs-ajax-success="PagerRequestSuccess"
              cs-ajax-failure="PagerRequestFailure"
              asp-controller="Paging"
              asp-action="AjaxPage"
              asp-route-pagesize="@Model.Products.PageSize"></cs-pager>
</div>